Add option to sanitise HTML in QuillViewHTMLComponent
KillerCodeMonkey/ngx-quill pull request #1237
Opened 2021-05-05 08:33 UTC by rajeshwarkohli

Resolves #1235

2021-05-05 09:23 UTC, KillerCodeMonkey commented
@rajeshwarkohli nice work, but could you add a little testcase for it?

2021-05-05 12:58 UTC, KillerCodeMonkey requested changes
@rajeshwarkohli nice work, but could you add a little testcase for it?

2021-05-05 14:24 UTC, rajeshwarkohli commented
@KillerCodeMonkey thank you. added test cases for it

2021-05-06 05:02 UTC, KillerCodeMonkey approved these changes

2021-05-06 05:02 UTC, merged