feat: switch to signal inputs
KillerCodeMonkey/ngx-quill pull request #1835
Opened 2024-04-10 15:16 UTC by arturovt

This commit switches inputs to signal inputs to be compatible with zoneless change detection because everything should be a signal primitive. As such, its changes may be caught by the execution context. Every time a signal changes, it would schedule a change detection event, even in zoneless mode.

I didn't update `@Output()` to `output` because we still use `.observed` properties.

2024-04-12 07:45 UTC, KillerCodeMonkey commented on projects/ngx-quill/src/lib/helpers.ts
> +export function raf$() {
would be nice to use fat arrow functions

2024-04-12 08:06 UTC, KillerCodeMonkey requested changes
And CI is failing coverage now.

maybe test your request animation helper.

other better the destroy callback

2024-04-12 14:40 UTC, arturovt commented
No matter what tests I add the coverage remains the same.

2024-04-15 05:37 UTC, KillerCodeMonkey approved these changes

2024-04-15 05:37 UTC, KillerCodeMonkey commented
i will check it thank you for the pr

2024-04-15 05:38 UTC, merged

2024-04-15 19:07 UTC, KillerCodeMonkey commented
FYI: it is the coverage for branches

if you run the test -> check the coverage folder there you have the text, json and html coverage reports

2024-04-19 13:06 UTC, arturovt commented
@andrei-varchanka, you don't need to upgrade to the latest version if you're staying with Angular versions lower than 17, as the latest changes are only compatible with ng17.